name: ci-go

on:
  push:
    branches:
      - main
      - dev
      - non-k8s
  pull_request:
    branches:
      - main
      - dev
      - non-k8s

jobs:
  go-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: v1.17

      - name: Check gofmt on src/service
        run: make -C src/service gofmt

      - name: Check gofmt on src/operator
        run: make -C src/operator gofmt

  go-sec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: v1.17

      - name: Run Gosec Security Scanner on src/service
        run: make -C src/service gosec

      - name: Run Gosec Security Scanner on src/operator
        run: make -C src/operator gosec

  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: golangci-lint on src/service
        with:
          working-directory: src/service
          args: --timeout=300s
        uses: golangci/golangci-lint-action@v2

      - name: golangci-lint on src/operator
        with:
          working-directory: src/operator
          args: --timeout=300s
        uses: golangci/golangci-lint-action@v2
