name: ci-minikube

on:
  push:
    branches:
      - main
      - dev
      - non-k8s
    pull_request: 
      branches:
        - main
        - dev
        - non-k8s

jobs:
  build:
    name: Auto-testing Framework / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,ubuntu-18.04]
    steps:
      - name: Check Docker Version
        run: uname -r
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - uses: actions/checkout@v2

      - name: Install Minikube
        run: |
          set -x
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
          sudo dpkg -i minikube_latest_amd64.deb
          rm minikube_latest_amd64.deb
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo mv kubectl /usr/bin
          sudo chmod 755 /usr/bin/kubectl
      
      - name: Start Minikube
        run: minikube start
      
      - name: Exposing host to machine
        run : minikube tunnel &
      
      - name: Apply VM and Hostpolicy CRD
        run: |
          sleep 10
          minikube kubectl -- apply -f ./deployments/etcd.yml
          minikube kubectl -- apply -f ./deployments/CRD/KubeArmorVirtualMachine.yaml
          minikube kubectl -- apply -f ./deployments/CRD/KubeArmorHostPolicy.yaml
      
      - name: Check the ip
        run: minikube ip
      
      - name: Deploy kvmsoperator and kvmservice in minikube
        run: |
          minikube kubectl -- apply -f ./src/operator/kvmsoperator.yaml
          minikube kubectl -- apply -f ./src/service/kvmservice.yaml
      
      - name: Configure new VM
        run: minikube kubectl -- apply -f ./examples/kvmpolicy1.yaml

#       - name: Checking the logs
#         run: kubectl logs $(minikube kubectl -- get pods,svc -A | grep pod/kvmsoperator | cut -d ' ' -f 4 | cut -d '/' -f 2) --namespace kube-system
      
      - name: Installing Karmor
        run: curl -sfL https://raw.githubusercontent.com/kubearmor/kubearmor-client/main/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Running karmor
        run: |
          sleep 10
          minikube kubectl -- get pods,svc -A
          karmor vm getscript -v testvm1
      
      - name: Run The Script
        run: bash ./testvm1.sh
